### ISSUE TITLE
Add flexible output saving options, add in-memory output

### ISSUE THREAD

**Issue by ykharkov** [amazon-braket/tensor-network-ahs#5]
- Currently all types of artifacts are saved by default at the end of the simulation (samples, density <n>, correlator <Z_i Z_j>). Enable granular options to specify which output data to save. 
- In addition to saving the outputs on a disk, add in-memory function output as a JSON file.

**Comment by virajvchaudhari** [comment]
Thank you for this issue! We will look into this.

**Comment by ykharkov** [comment]
Closing the issue, resolved in https://github.com/amazon-braket/tensor-network-ahs/pull/6
